package softixx.api.payment.stripe;

import lombok.Builder;
import lombok.Builder.Default;
import lombok.Data;
import softixx.api.util.UPayment;

/**
 * This bean contains all the attributes that you need for a payment with Stripe <br><br>
 * Attributes <br>
 * {@value} <b>currency</b> (String) - Currency (Has to be either mxn or usd) <b><i>*Required</i></b> <br>
 * {@value} <b>amount</b> (Double) - Amount intended to be collected by this payment <b><i>*Required</i></b> <br>
 * {@value} <b>source</b> (String) - Previously generated by Stripe <br>
 * {@value} <b>description</b> (String) - Item name or description <br>
 
 * @see UPayment
 */
@Data
@Builder
public class StripeData {
	private String source;
	private String description;
	@Default
	private String currency = UPayment.PAYMENT_CURRENCY_MXN;
	private Double amount;
	private String customerId;
	@Default
	private Boolean sendEmail = false;
	private String receiptEmail;
}
